# Generated by Django 3.2 on 2022-11-17 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0002_alter_uploadfile_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadfile',
            name='file',
        ),
        migrations.AddField(
            model_name='uploadfile',
            name='file_up',
            field=models.FileField(null=True, upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='uploadfile',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
